name: Deploy job

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true

jobs:
  deploy-and-comment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.x]
    steps:
      - uses: actions/checkout@v2

      - name: 'Deploy application'
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            prodRun="--prod"
          fi

          echo "::set-output name=test-url::$(npx vercel --yes --token ${VERCEL_TOKEN} $prodRun)"
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        if: github.ref != 'refs/heads/master'
        with:
          body: |
            **Deployed Successfully** :white_check_mark:
            - You can test on this url: ${{ steps.deploy.outputs.test-url }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: github.event_name == 'pull_request'
        with:
          message: |
            **Deployed Successfully** :white_check_mark:
            - You can test on this url: ${{ steps.deploy.outputs.test-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
